[project]
name = "SimPEG-pixi"
version = "0.1.0"
description = "Add a short description here"
authors = ["nieboer <roeland.nieboer@deltares.nl>"]
channels = ["conda-forge"]
platforms = ["linux-64", "win-64", "osx-arm64", "osx-64"]

[tasks]

[dependencies]
python = ">=3.12.2,<3.13"
simpeg = ">=0.20.0,<0.21"
